logging:
  type: syslog
  level: log_info

components:
  - libfuse
  - block_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

block_cache:
  block-size-mb: 16
  mem-size-mb: 4096
  buffer-size-mb: 16

attr_cache:
  timeout-sec: 7200

azstorage:
  type: block
  mode: msi